web/geochats/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from rest_framework import routers

from . import views
from .views import MessageViewSet

router = routers.SimpleRouter()
router.register(r'messages', MessageViewSet, basename='Message')
urlpatterns = router.urls

app_name = 'geochats'
urlpatterns += [
    path('', views.index, name='index'),
    path('logout', LogoutView.as_view()),
    path('auth/signup/', views.signup, name='signup'),
    path('auth/login/', views.signup, name='login'),
    path('get-location/', views.ajax_get_location, name='ajax-location'),
    path('save-user/', views.ajax_save_user, name='ajax-save-user'),
    path('room/', views.room, name='room'),
    path('map-test/', views.map_test, name='map-test')
]

web/localchats/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path('', include('geochats.urls')),
    path('admin/', admin.site.urls),
]

web/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.base_user import BaseUserManager


class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    email = models.EmailField('Email', unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    def get_username(self):
        return self.username

    def update_username(self, new_username):
        self.username = new_username
        self.save()
        return self.username


class AnonymousUser(models.Model):
    id = models.AutoField(primary_key=True)

    def get_username(self):
        try:
            return self.username_set.all().last().username
        except AttributeError:
            return f'user#{self.id}'

    def get_username_instance(self):
        try:
            return self.username_set.all().last()
        except AttributeError:
            return None

    def update_username(self, new_username):
        print("OK")
        u = self.username_set.create(
            username=new_username,
            user=self
        )
        print("OK 2")
        u.save()
        self.save()
        return self.get_username()


class Username(models.Model):
    user = models.ForeignKey(AnonymousUser, on_delete=models.CASCADE)
    username = models.CharField(max_length=100, default="user")

web/geochats/models.py
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.contrib.gis.db import models
from django.contrib.gis.geos import Point
from django.db.models.signals import post_save

from accounts.models import User, Username


class Chat(models.Model):
    location = models.PointField(geography=True, default=Point(0.0, 0.0))


class Message(models.Model):
    text = models.CharField(max_length=500)
    chat = models.ForeignKey(Chat, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)


class AnonMessage(models.Model):
    username = models.ForeignKey(Username, on_delete=models.SET_NULL, null=True)
    message = models.OneToOneField(Message, on_delete=models.CASCADE)

    def get_username(self):
        try:
            return self.username.username
        except AttributeError:
            return "user"

    def get_user_id(self):
        try:
            return self.username.user_id
        except (User.DoesNotExist, AttributeError):
            return None


class AuthMessage(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.OneToOneField(Message, on_delete=models.CASCADE)

    def get_username(self):
        return self.user.username

    def get_user_id(self):
        return self.user_id

web/accounts/views.py
from django.shortcuts import render

# Create your views here.

web/geochats/views.py
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.contrib.gis.geos import Point
from rest_framework import viewsets
from rest_framework.response import Response

from geochats.models import AnonMessage, AuthMessage, Chat
from geochats.services import (
    update_room_id
)
from geochats.serializers import MessageSerializer
from accounts.models import AnonymousUser


def index(request):
    return render(request, 'geochats/index.html', {})


def room(request):
    return render(request, 'geochats/room.html',
                  {
                      'messages': None,
                      'user': None
                  })


from django.views.decorators.csrf import csrf_exempt


@csrf_exempt
def ajax_save_user(request):
    user_id = request.POST.get('user_id', None)

    if user_id:
        request.session['anon_user_id'] = user_id
    return JsonResponse({'success': "Ok"})


def ajax_get_location(request):
    request.session['lat'] = request.GET['lat']
    request.session['lng'] = request.GET['lng']
    # print(request.session[])
    request.session['timezone'] = request.GET['time_offset']
    old_chat = request.session.get('room_id')

    update_room_id(request)
    new_chat = request.session['room_id']
    if old_chat != new_chat:
        context = {
            'updated': True
        }
    else:
        context = {
            'updated': False
        }
    return JsonResponse(context)


class MessageViewSet(viewsets.ViewSet):
    def list(self, request):
        queryset = AuthMessage.objects.all()
        serializer = MessageSerializer(queryset, many=True)
        return Response(serializer.data)

    def retrieve(self, request, pk=None):
        queryset = AuthMessage.objects.all()
        message = get_object_or_404(queryset, pk=pk)
        serializer = MessageSerializer(message)
        return Response(serializer.data)


from .services import key_sector_coords


def map_test(request):
    points = []
    for i in Chat.objects.all():
        points.append([i.location[0], i.location[1]])
    points.append([key_sector_coords[1], key_sector_coords[0]])
    points.append([30.52504, 50.43216])
    context = {
        # 'points': [[30.1345542, 50.8018212], [30.1303865, 50.8059638]]
        'points': points
    }

    return render(request, 'geochats/map-test.html', context)


def signup(request):
    return render(request, 'registration/signup.html')

web/templates/base.html
<!doctype html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
            integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600;700;800&display=swap"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet">
    <link rel="stylesheet" href="{% static 'geochats/fonts/shrimp/stylesheet.css' %}">

    <title>{% block title %}LocalChats{% endblock %}</title>
</head>
<body>
{% block content %}
{% endblock content %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
        crossorigin="anonymous"></script>

</body>
</html>

web/templates/geochats/index.html
{% extends 'base.html' %}
{% block title %}Nearest{% endblock title %}
{% block content %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'geochats/styles/main.css' %}">
    <link rel="stylesheet" href="{% static 'geochats/styles/info.css' %}">

    <div class="container-fluid p-0">

        <div class="row m-0" style="height:100vh; position:relative;">

            <div class="col-lg-5 col-12 d-flex justify-content-start align-items-end pb-5" style="position: relative">
                <div class="logo">
                    <img src="{% static "geochats/img/logo.svg" %}" class="img-fluid">
                    <span>make connection<br/>with people around you</span>
                </div>
                <div class="planet" style="padding-top: 100px">
                    <p>NEAREST</p>
                    <img src="{% static "geochats/img/planet.svg" %}" class="img-fluid">
                </div>
            </div>
            <div class="col-lg-7 col-12 info d-flex align-items-center justify-content-around"
                 style="padding-bottom:15%;">
                <img src="{% static "geochats/img/info-lines.svg" %}" class="info-lines">
                <div class="info-square info-square-medium mb-2">
                    <span>at any</span>
                    <span style="color:#FF7B7B">place</span>
                </div>
                <div class="info-square info-square-big">
                    <span style="color:#FF7B7B">free</span>
                    <span>of charge</span>
                </div>
                <div class="info-square info-square-medium mt-5">
                    <span>at any</span>
                    <span style="color:#FF7B7B">time</span>
                </div>
                <div class="cta">
                    <a href="{% url 'geochats:signup' %}">Sign Up</a>
                    <div style="font-size:25px;">or</div>
                    <a href="{% url 'geochats:room' %}">Use anonymously</a>
                </div>
            </div>

        </div>
        <div class="row m-0" style="height:100vh; width:100%">
            <div class="col-12 d-flex justify-content-center align-items-center">
                <object type="image/svg+xml" data="{% static "geochats/img/chat-center.svg" %}" style="width:50%"></object>
            </div>
        </div>
        <div class="row m-0" style="height:100vh; width:100%; position:relative;">
            <div class="col-sm-5 d-flex justify-content-center align-items-center">
                <img src="{% static "geochats/img/auto-connection.svg" %}" class="img-fluid">
            </div>
            <div class="col-sm-6 d-flex justify-content-center align-items-start flex-column">
                <p class="title">AUTOMATIC CONNECTION</p>
                <p class="subtitle">A system automatically connects you to the nearest chats available</p>
            </div>
        </div>
        <div class="row m-0"
             style="height:100vh; width:100%; position:relative; background-color: #80C1C1; color:white;">

            <div class="offset-md-1 col-md-6 col-12 d-flex justify-content-center align-items-center align-items-md-start flex-column">
                <p class="title">CHOOSE PRIVACY</p>
                <p class="subtitle">
                    Only you decide what to share and to which people. Choose from one of three levels of privacy.<br/>
                    1 - anonymously with username change on every page reload.<br/>
                    2 - anonymously with choosing username you want and saving it.<br/>
                    3 - with created account but still with possibility to change username.
                </p>
            </div>
            <div class="col-md-5 col-12 d-flex justify-content-center align-items-center">
                <img src="{% static "geochats/img/privacy.svg" %}" class="img-fluid">
            </div>
        </div>
    </div>

{% endblock content %}

web/templates/geochats/map-test.html
<!doctype html>
<html lang="en">
<head>
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.5.0/css/ol.css"
          type="text/css">
    <style>
        .map {
            height: 90vh;
            width: 100%;
        }
    </style>
    <script src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.5.0/build/ol.js"></script>
    <title>OpenLayers example</title>
</head>
<body>
<h2>Chats Map</h2>
<div id="map" class="map"></div>
<script type="text/javascript">
    import {getPointResolution} from 'ol/proj';

    function drawCircleInMeter(map, radius) {
        var view = map.getView();
        var projection = view.getProjection();
        var resolutionAtEquator = view.getResolution();
        var center = map.getView().getCenter();
        console.log(center)
var pointResolution = getPointResolution(projection, resolutionAtEquator, center);        var resolutionFactor = resolutionAtEquator / pointResolution;
        var radius = (radius / ol.proj.METERS_PER_UNIT.m) * resolutionFactor;


        var circle = new ol.geom.Circle(center, radius);
        var circleFeature = new ol.Feature(circle);

        // Source and vector layer
        var vectorSource = new ol.source.Vector({
            projection: 'EPSG:4326'
        });
        vectorSource.addFeature(circleFeature);
        var vectorLayer = new ol.layer.Vector({
            source: vectorSource
        });

        map.addLayer(vectorLayer);
    }

    var map = new ol.Map({
        target: 'map',
        layers: [
            new ol.layer.Tile({
                source: new ol.source.OSM()
            })
        ],
        view: new ol.View({
            center: ol.proj.fromLonLat([30.52504, 50.43216]),
            zoom: 20
        })
    });


    var layer = new ol.layer.Vector({
        source: new ol.source.Vector({
            features: [
                {% for point in points %}

                    new ol.Feature({
                        geometry: new ol.geom.Point(ol.proj.fromLonLat({{ point }}))
                    }),
                {% endfor %}
            ]
        })
    });
    map.addLayer(layer);
    {% for point in points %}
        drawCircleInMeter(map, 50000)
    {% endfor %}
</script>
</body>
</html>

web/templates/geochats/room.html
{% extends 'base.html' %}
{% block content %}
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
            integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>

    {% load static %}
    {% load geochats_extras %}
    <link rel="stylesheet" href="{% static 'geochats/styles/main.css' %}">
    <span class="user-header">{{ user.username }}#{{ user.id }}</span>
    <span class="room-header">Room <span></span></span>

    <div class="row navbar" id="navbar-main">


        <div class="col-sm-12 nav d-flex justify-content-center align-items-end h-100 pb-5">
            <div class="open-menu">
<span class="material-icons-outlined material-icons open-menu-arrow noselect">
keyboard_arrow_down
</span>
            </div>
            <div class="username-change">
                <label for="username" class="mb-3">Change your username</label>
                <input name="username" placeholder="username">
            </div>
            <div class="logo-text">
                <img src="{% static 'geochats/img/logo.png' %}" class="img-fluid noselect" style="max-height:80px;">
                <div class="logo-subtitle">NEAREST</div>
            </div>
        </div>
    </div>
    <div class="scroll-bottom" id="scroll-bottom-arrow">
<span class="material-icons-outlined material-icons scroll-bottom-arrow">
keyboard_arrow_down
</span>
    </div>
    <div class="container-fluid">
        <div class="row pt-5 messages">
            <div class="offset-sm-3 col-sm-6 message-container" id="chat-log">
                {% for message in messages %}
                    <div class="row w-100">
                        <div class="col-12">
                            <div class="message-bubble">
                                <div class="message-meta">
                                    <div class="username">
                                        {% if message.user %}{{ message.user.username }}#{{ message.user.id }}{% else %}
                                            Anon{% endif %}</div>
                                    <div class="date">{{ message.date|convert_timezone:request.session.timezone|time }}</div>
                                </div>
                                <div>{{ message.text }}</div>
                            </div>

                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="row message-input w-sm-100 w-md-75">
            <div class="col-sm-12">
                <span class="connection-status" id="connection-status"></span>
                <input id="chat-message-input" type="text" placeholder="Write a message...">
                <input id="chat-message-submit" type="button" value="Send" class="w-25 mt-3"
                       style="visibility: hidden">
            </div>
        </div>
    </div>
    {#    <script src="https://cdn.jsdelivr.net/npm/js-cookie@rc/dist/js.cookie.min.js"></script>#}

    <script>
        function saveUser(user_id) {
            console.log(user_id, 'sending...')
            $.ajax({
                type: "POST",
                url: "{% url 'geochats:ajax-save-user' %}",
                data: {
                    'user_id': user_id,
                    {#csrfmiddlewaretoken: Cookies.get('csrftoken')#}
                },
                success: function (data) {
                    console.log("user id was successfully save to session storage")
                },

                dataType: 'json'
            });
        }
    </script>
    <script type="text/javascript" src="{% static "geochats/js/websocket-handler.js" %}"></script>
    <script type="text/javascript" src="{% static "geochats/js/script.js" %}"></script>

{% endblock content %}